### ISSUE TITLE
routing to db

### ISSUE THREAD

**Issue by wiepke** [juliandehne/fltrail#34]
transformationRoutes.scala builds different routes for every transformator and sends individual calls to db. It is possibly faster to collect all transformated data and send the collection to the db.

**Comment by juliandehne** [comment]
I think i was afraid of the stale cache problem. We will see how it pans out.

**Comment by juliandehne** [comment]
We checked the timings. It turns out the bottlenex is the Kreuzprodukt in using the Germanet route.
